from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class TherapistSummary(BaseModel):
    """Clinical summary produced by Gemini from the user's journal + chat.

    Generated by `THERAPIST_SUMMARY_SYSTEM`; consumed as input to the matcher.
    """

    summary_for_therapist: str
    key_concerns: list[str] = Field(default_factory=list)
    emotion_pattern: str = ""
    suggested_focus_areas: list[str] = Field(default_factory=list)
    crisis_indicators: str = "none detected"
    user_strengths: str = ""


class TherapistMatchRequest(BaseModel):
    therapist_summary: TherapistSummary
    # 9 emotion scores in [0, 1] mirroring `EmotionScores`.
    user_emotions: dict[str, float] = Field(default_factory=dict)
    language: Literal["korean", "japanese", "both"] = "both"


class TherapistProfile(BaseModel):
    """Full therapist record as returned to the frontend."""

    therapist_id: str
    name: str
    location: str
    languages: list[str]
    certifications: list[str]
    approach: list[str]
    specializes_in: list[str]
    emotions_treated: list[str]
    online_available: bool
    in_person_available: bool
    years_experience: int | None = None
    education: str | None = None
    bio: str | None = None
    price_per_session: str | None = None
    rating: float | None = None

    model_config = ConfigDict(from_attributes=True)


class TherapistRanking(BaseModel):
    """One item in Gemini's ranked output (Layer 2)."""

    therapist_id: str
    match_score: float = Field(..., ge=0.0, le=1.0)
    match_reason: str
    matched_concerns: list[str] = Field(default_factory=list)
    approach_fit: str = ""


class TherapistRankingList(BaseModel):
    """Wrapper so Gemini `response_schema` can take a Pydantic model
    (top-level lists aren't directly accepted)."""

    rankings: list[TherapistRanking]


class TherapistMatch(TherapistProfile):
    """Final result row — therapist profile + match metadata."""

    match_score: float
    match_reason: str
    matched_concerns: list[str] = Field(default_factory=list)
    approach_fit: str = ""


class TherapistMatchResponse(BaseModel):
    top_matches: list[TherapistMatch]
    total_candidates_evaluated: int
    layer1_filtered: int
    matching_method: str = "two-layer: mathematical + AI semantic"
